-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_postcodeat`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_postcodeat
-- *
-- *******************************************************/
CREATE TABLE `civicrm_postcodeat` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Unique PostcodeAT ID',
  `gemnr` char(5) NOT NULL COMMENT 'Municipality code',
  `gemnr2` char(5) NOT NULL COMMENT 'Municipality code 2',
  `gemnam38` char(50) NOT NULL COMMENT 'Municipality name',
  `okz` char(5) NOT NULL COMMENT 'Town/village code',
  `ortnam` char(50) NOT NULL COMMENT 'Town/village name',
  `skz` char(6) NOT NULL COMMENT 'Street code',
  `stroffi` varchar(60) NOT NULL COMMENT 'Street name',
  `strkurz` varchar(50) NULL COMMENT 'Street short name',
  `plznr` char(4) NOT NULL COMMENT 'ZIP code',
  `zustort` varchar(75) NULL COMMENT 'Municipality',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
